exclude: >
  (?x)^(
      .+/.venv/.+|
      .+/dist/.+|
      .+/.autovenv|
      .+/build/.+|
      .+/\.eggs/.+|
      .+/\.tox/.+|
      .+/\.pytest_cache/.+|
      .+/\.coverage|
      .+/\.mypy_cache/.+|
      .+/\.ruff_cache/.+|
      .+/\.git/.+
  )$
fail_fast: true
default_language_version:
  python: python3
default_stages:
  - prepare-commit-msg
  - pre-commit
  - pre-push
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=1000]
        stages:
          - pre-commit
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key
      - id: destroyed-symlinks
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        exclude: \.pre-commit-config\.yaml|mkdocs\.yml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.8.6"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.8.6"
    hooks:
      - id: ruff
        args: ["--fix", "--unsafe-fixes"]
        files: \.pyi?$
        exclude: \.pre-commit-config\.yaml
      - id: ruff-format
        args: []
        files: \.pyi?$
        exclude: \.pre-commit-config\.yaml

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.5.0"
    hooks:
      - id: pyproject-fmt
        # https://pyproject-fmt.readthedocs.io/en/latest/#calculating-max-supported-python-version
        additional_dependencies: ["tox>=4.9"]
