site_name: virtuals-python
repo_url: https://github.com/Virtual-Protocol/virtuals-python
site_url: https://Virtual-Protocol.github.io/virtuals-python
site_description: Official Python SDK for Virtuals API/GAME
site_author: Chethan UK
edit_uri: edit/main/docs/
repo_name: Virtual-Protocol/virtuals-python
copyright: Maintained by <a href="https://Virtual-Protocol.com">Virtual-Protocol</a>.

nav:
  - Home: index.md
  - API Reference:
      - Core:
          - GameSDK: api/core/sdk.md
      - Game:
          - Game: api/core/game.md
          - Agent: api/core/agent.md
      - Functions:
          - Telegram: api/functions/telegram.md
          - Discord: api/functions/discord.md

dev_addr: 127.0.0.1:8003

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python-requests.org/en/master/objects.inv
          selection:
            docstring_style: google
            inherited_members: true
            filters: ["!^_", "!^__init__$"]
            members: true
          paths: [src]
          options:
            show_source: true
            show_root_heading: true
            show_object_full_path: false
            show_category_heading: true
            show_bases: true
            group_by_category: true
            heading_level: 2
            members_order: source
            docstring_section_style: table
            show_signature_annotations: true
            merge_init_into_class: true
            separate_signature: true
            show_if_no_docstring: true
            docstring_options:
              replace_admonitions: true
            show_submodules: true
            recursive: true

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: "."
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
